// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/drawings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/drawings.get').default>>>>
    }
    '/api/feed': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feed.get').default>>>>
    }
    '/api/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/generate.post').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/auth/anonymous': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/anonymous.get').default>>>>
    }
    '/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/github.get').default>>>>
    }
    '/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/google.get').default>>>>
    }
    '/drawings/**:pathname': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/drawings/[...pathname].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.2_@netlify+blobs@9.1.2_@vercel+blob@2.0.0_aws4fetch@1.0.20_db0@0_65168dea0ae291bc2b57cbe73f090854/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.1.1_magicast@0.5.1_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1_lightningcss@1_a97ff1c1640e92e38c9e8ac2ce323128/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.26_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.26_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
  }
}
export {}