// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-auth-utils@0.5.26_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/app/plugins/session.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1_lightningcss@1.30.2_terse_f9b5fe2701ce96fe1c3b9ee19b4b818d/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1_lightningcss@1.30.2_terse_f9b5fe2701ce96fe1c3b9ee19b4b818d/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-auth-utils@0.5.26_magicast@0.5.1/node_modules/nuxt-auth-utils/dist/runtime/app/plugins/session.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@4.3.0_65b4ad8c403ece7d05bff0a302e28c45/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@2.1.1_magicast@0.5.1_vite@7.3.0_@types+node@25.0.3_jiti@2.6.1_lightningcss@1_a97ff1c1640e92e38c9e8ac2ce323128/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@netlify+blobs@9.1.2_@parcel+watcher@2.4.1_@types+node@25.0.3_@vercel+blob@2_86d3e61ceeef8d2f853148adeee855fb/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../app/plugins/auth-state.server")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'session-fetch-plugin' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
