// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sponge/internal/api/v1"
	"sponge/internal/dao"
	"sponge/internal/router"
	"sponge/internal/server"
	"sponge/internal/service"
)

// Injectors from wire.go:

func InitApp() (*server.HttpServer, func(), error) {
	userDao := dao.NewUserDao()
	userService := service.NewUserService(userDao)
	userApi := v1.NewUserApi(userService)
	routerGroup := router.NewRouterGroup(userApi)
	httpServer := server.NewHttpServer(routerGroup)
	return httpServer, func() {
	}, nil
}
