// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sponge/internal/api/v1"
	"sponge/internal/dao"
	"sponge/internal/router"
	"sponge/internal/server"
	"sponge/internal/service"
)

// Injectors from wire.go:

func InitApp() (*server.HttpServer, func(), error) {
	userDao := dao.NewUserDao()
	userService := service.NewUserService(userDao)
	userApi := v1.NewUserApi(userService)
	videoDao := dao.NewVideoDao()
	likeDao := dao.NewLikeDao()
	videoService := service.NewVideoService(videoDao, userDao, likeDao)
	likeService := service.NewLikeService(likeDao, videoDao)
	videoApi := v1.NewVideoApi(videoService, userService, likeService)
	followDao := dao.NewFollowDao()
	followService := service.NewFollowService(followDao, userDao)
	followApi := v1.NewFollowApi(followService, userService)
	likeApi := v1.NewLikeApi(likeService, videoService, userService)
	commentDao := dao.NewCommentDao()
	commentService := service.NewCommentService(commentDao, videoDao)
	commentApi := v1.NewCommentApi(commentService, userService)
	chatDao := dao.NewChatDao()
	chatService := service.NewChatService(chatDao, userDao)
	chatApi := v1.NewChatApi(chatService, userService)
	routerGroup := router.NewRouterGroup(userApi, videoApi, followApi, likeApi, commentApi, chatApi)
	httpServer := server.NewHttpServer(routerGroup)
	return httpServer, func() {
	}, nil
}
