// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sponge/internal/api/v1"
	"sponge/internal/dao"
	"sponge/internal/server"
	"sponge/internal/service"
)

// Injectors from wire.go:

// InitApp 依赖注入入口
// Wire 会分析依赖关系：Server 依赖 API -> API 依赖 Service -> Service 依赖 DAO
func InitApp() (*server.HttpServer, func(), error) {
	userDao := dao.NewUserDao()
	userService := service.NewUserService(userDao)
	userApi := v1.NewUserApi(userService)
	httpServer := server.NewHttpServer(userApi)
	return httpServer, func() {
	}, nil
}
